force-app/main/default/objects/ES_Phase__c/ES_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Inspection. Phases can have tasks associated with them.</description>
    <label>ES Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ES Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ES_Phase__c/fields/Health_Icon__c.field-meta.xml
<CustomField>
    <fullName>Health_Icon__c</fullName>
    <formula>IMAGE(
CASE(Phase_Health__c,
&quot;Not Started&quot;, &quot;/resource/ES_Status_logos/Not_Started.png&quot;,
&quot;On Track&quot;, &quot;/resource/ES_Status_logos/On_Track.png&quot;,
&quot;At risk&quot;, &quot;/resource/ES_Status_logos/At_Risk.png&quot;,
&quot;Late&quot;, &quot;/resource/ES_Status_logos/Late.png&quot;,
&quot;On Hold&quot;, &quot;/resource/ES_Status_logos/On_Hold.png&quot;,
&quot;Completed&quot;, &quot;/resource/ES_Status_logos/Completed.png&quot;,
&quot;Closed, not Completed&quot;, &quot;/resource/ES_Status_logos/Closed_not_Completed.png&quot;,
&quot;/resource/ES_Status_logos/On_Track.png&quot;),
&quot;status icon&quot;,25,25)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Health</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ES_Phase__c/fields/Kickoff_formula__c.field-meta.xml
<CustomField>
    <fullName>Kickoff_formula__c</fullName>
    <formula>IF(ISNULL(Start_Date_Rollup__c),  IF(ISNULL( Start_date_from_child_Inspection__c), Inspection__r.Kickoff_formula__c, Start_date_from_child_Inspection__c) ,Start_Date_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ES_Phase__c/fields/Phase_Completion_Image__c.field-meta.xml
<CustomField>
    <fullName>Phase_Completion_Image__c</fullName>
    <formula>IMAGE(&quot;/resource/ES_Status_Images/ES_Percent_100.jpg&quot;, &quot;Completed&quot;, 10, ( Phase_Completion__c * 100 )/1.3) &amp; 
IMAGE(&quot;/resource/ES_Status_Images/ES_Percent_0.jpg&quot;, &quot;Zero&quot;, 10, (100 - Phase_Completion__c * 100 )/1.3) &amp; 
&apos; &apos; &amp; 
TEXT(ROUND(Phase_Completion__c * 100,0))&amp;&quot;%&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Completion</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ES_Task__c/ES_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>ES Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ES Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ES_Task__c/fields/Inspection_Id__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Id__c</fullName>
    <formula>CASESAFEID(Phase__r.Inspection__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inspection Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ES_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>ES_Phase__c</referenceTo>
    <relationshipLabel>ES Tasks</relationshipLabel>
    <relationshipName>Inspection_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ES_Task__c/fields/Status_Icon__c.field-meta.xml
<CustomField>
    <fullName>Status_Icon__c</fullName>
    <formula>IF(AND(Days_Late__c &gt;0,TEXT(Status__c) &lt;&gt; &quot;On Hold&quot;),IMAGE(&quot;/resource/ES_Status_Images/ES_warning_60.png&quot;,&quot;Late&quot;,20,20), 
IF( TEXT(Sign_off_status__c) = &quot;Approved&quot;, IMAGE(&quot;/resource/ES_Status_Images/ES_approval.png&quot;,&quot;Approved&quot;,20,20), 
CASE( TEXT(Status__c) , 
&quot;Not Started&quot;, IMAGE(&quot;/resource/ES_Status_Images/ES_routing_offline_60.png&quot;,&quot;Incomplete&quot;,20,20), 
&quot;In Progress&quot;, IMAGE(&quot;/resource/ES_Status_Images/ES_Clock.png&quot;,&quot;In Progress&quot;,20,20), 
&quot;On Hold&quot;,IMAGE(&quot;/resource/ES_Status_Images/ES_error_60.png&quot;,&quot;On Hold&quot;,20,20), 
IMAGE(&quot;/resource/ES_Status_Images/ES_success_60.png&quot;,&quot;Closed&quot;,20,20))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inspection__c/Inspection__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A Inspection can one or more phases</description>
    <label>ES Inspection</label>
    <nameField>
        <label>Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ES Inspections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection__c/fields/Health_Icon__c.field-meta.xml
<CustomField>
    <fullName>Health_Icon__c</fullName>
    <description>Icon corresponding to status of the project.</description>
    <formula>IMAGE(
CASE(Project_Health__c,
&quot;Not Started&quot;, &quot;/resource/ES_Status_logos/Not_Started.png&quot;,
&quot;On Track&quot;, &quot;/resource/ES_Status_logos/On_Track.png&quot;,
&quot;At risk&quot;, &quot;/resource/ES_Status_logos/At_Risk.png&quot;,
&quot;Late&quot;, &quot;/resource/ES_Status_logos/Late.png&quot;,
&quot;On Hold&quot;, &quot;/resource/ES_Status_logos/On_Hold.png&quot;,
&quot;Completed&quot;, &quot;/resource/ES_Status_logos/Completed.png&quot;,
&quot;Closed, not Completed&quot;, &quot;/resource/ES_Status_logos/Closed_not_Completed.png&quot;,
&quot;/resource/ES_Status_logos/On_Track.png&quot;),
&quot;status icon&quot;,25,25)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Health</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ES_ProjectSummaryCtrl.cls
/******************************************************************************
* Name: ES_InspectionSummaryCtrl.apxc
* Used by: Used by ES_InspectionSummaryPhaseTable.cmp
* Description : It contains methods to find out phases, tasks, milestones related to ES Inspection
* Test class : ES_Testcoverage(85%)
******************************************************************************/

public with sharing class ES_InspectionSummaryCtrl {

    /*************************************************
    * Name: createSummaryWrapper
    * Description: Create wrapper for lists
    * ***********************************************/
  
    public class CreateSummaryWrapper
    {
        @AuraEnabled public List<ES_Phase__c> phasesList;
        @AuraEnabled public List<ES_Task__c> lateTaskList;
        @AuraEnabled public List<ES_Task__c> onGoingTaskList;
        @AuraEnabled public List<ES_Task__c> milestoneTaskList;
        @AuraEnabled public integer fiscalMonthOffset;
    }
    
    /************************************************
    * Method Name: getSummaryWrapper 
    * Description: Wrapper for getPhasesForInspection and getTasksForInspection methods
    * Parameters : recordId
    * Return Values: list of Tasks and list of phases
    * ***********************************************/    
    @AuraEnabled
    public static CreateSummaryWrapper getSummaryWrapper(Id recordId)
    {
        CreateSummaryWrapper summaryWrapper = new CreateSummaryWrapper();
        //Calling util method to check CRUD
        List<String> lstOfPhaseFields = new List<String>{'Name', 'Health_Icon__c', 'Phase_Completion__c', 'Phase_Completion_Image__c', 'ES_Inspection__c','Kickoff_formula__c'};
        if (ES_Utility.validateCRUD('ES_Phase__c', lstOfPhaseFields, 'isAccessible') ){ 
            summaryWrapper.phasesList = getPhasesForInspection(recordId);
        }else{
            throw new AuraHandledException('You don\'t have access to ES Phases. Please contact system administrator.');
        }
        
        //Calling util method to check CRUD
        List<String> lstOfTaskFields = new List<String>{'Name', 'Status_Icon__c', 'Start_Date__c', 'Due_Date__c', 'Is_Milestone__c', 'Phase__c', 'Days_Late__c', 'Inspection_Id__c'};
        if (ES_Utility.validateCRUD('ES_Task__c', lstOfTaskFields, 'isAccessible') ){ 
            summaryWrapper.lateTaskList = getLateTasksForInspection(recordId);
            
            summaryWrapper.onGoingTaskList = getOnGoingTasksForInspection(recordId);
            
            summaryWrapper.milestoneTaskList = getMilestoneTasksForInspection(recordId);
        }else{
            throw new AuraHandledException('You don\'t have access to ES Task. Please contact system administrator.');
        }       
        
        //Get ES Settings
        summaryWrapper.fiscalMonthOffset = Integer.valueOf(ES_Utility.getESSettings('Default').Start_Month_of_Fiscal_Year__c);
        return summaryWrapper;      
    }
    
    /*************************************************
    * Method Name: getPhasesForInspection
    * Description: Get list of Phases for a Inspection
    * Parameters : recordId
    * Return Values: list of phases
    * ***********************************************/  
    private static List<ES_Phase__c> getPhasesForInspection(Id recordId)
    {
        return [SELECT id,Name,Health_Icon__c,Phase_Completion__c, Phase_Completion_Image__c,Kickoff_formula__c FROM ES_Phase__c 
                WHERE Inspection__c=:recordId ORDER BY Kickoff_formula__c ASC limit: limits.getLimitQueryRows()];                    
    }

    /*************************************************
    * Method Name: getLateTasksForInspection
    * Description: Get list of Tasks for a Inspection
    * Parameters : recordId
    * Return Values: list of late tasks
    * ***********************************************/  
    private static List<ES_Task__c> getLateTasksForInspection(Id recordId)
    {
        return [SELECT id,Name,Status_Icon__c,Start_Date__c,Due_Date__c,Is_Milestone__c,Phase__c,Days_Late__c FROM ES_Task__c 
                WHERE Inspection_Id__c=:recordId AND Days_Late__C > 0 order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];
    }

    /*************************************************
    * Method Name: getOnGoingTasksForInspection
    * Description: Get list of OnGoing Tasks set for a Inspection
    * Parameters : recordId
    * Return Values: list of ongoing tasks (not Late)
    * ***********************************************/  
    private static List<ES_Task__c> getOnGoingTasksForInspection(Id recordId)
    {
        return [SELECT id,Name,Status_Icon__c,Start_Date__c,Due_Date__c,Is_Milestone__c,Phase__c,Phase__r.Name,    Days_Late__c FROM ES_Task__c 
                WHERE Inspection_Id__c=:recordId AND Days_Late__C <= 0 order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];                        
    }

    /*************************************************
    * Method Name: getMilestoneTasksForInspection
    * Description: Get list of Milestone Tasks set for a Inspection
    * Parameters : recordId
    * Return Values: list of Milestone tasks
    * ***********************************************/  
    private static List<ES_Task__c> getMilestoneTasksForInspection(Id recordId)
    {
        return [SELECT id,Name,Status_Icon__c,Due_Date__c FROM ES_Task__c 
                WHERE Inspection_Id__c=:recordId AND Is_Milestone__c=true order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];                   
         
    }
    
}